
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 14;
  public static final int CHAR = 12;
  public static final int IGUALACION = 28;
  public static final int LLAVE2 = 42;
  public static final int LLAVE1 = 41;
  public static final int ENTERO = 3;
  public static final int XOR = 34;
  public static final int DOUBLE = 10;
  public static final int DOS_PUNTOS = 31;
  public static final int DIFEREN = 26;
  public static final int INT = 9;
  public static final int PRINTLN = 8;
  public static final int NOT = 35;
  public static final int FINCADENA = 7;
  public static final int AND = 33;
  public static final int IGUAL = 30;
  public static final int CARACTER = 6;
  public static final int OR = 32;
  public static final int BOOL = 39;
  public static final int IF = 38;
  public static final int UMENOS = 23;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 22;
  public static final int MENOS = 18;
  public static final int MAYOR_QUE = 25;
  public static final int PAR_C = 16;
  public static final int PAR_A = 15;
  public static final int POTENCIA = 21;
  public static final int ELSE = 40;
  public static final int MAYOR_IGUAL_QUE = 29;
  public static final int STRING = 11;
  public static final int MENOR_QUE = 24;
  public static final int FALSE = 37;
  public static final int DIVISION = 20;
  public static final int MENOR_IGUAL_QUE = 27;
  public static final int VAR = 13;
  public static final int MULTIPLICACION = 19;
  public static final int MAS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CARACTER",
  "FINCADENA",
  "PRINTLN",
  "INT",
  "DOUBLE",
  "STRING",
  "CHAR",
  "VAR",
  "CONST",
  "PAR_A",
  "PAR_C",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "UMENOS",
  "MENOR_QUE",
  "MAYOR_QUE",
  "DIFEREN",
  "MENOR_IGUAL_QUE",
  "IGUALACION",
  "MAYOR_IGUAL_QUE",
  "IGUAL",
  "DOS_PUNTOS",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "ELSE",
  "LLAVE1",
  "LLAVE2"
  };
}

