/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import excepciones.Errores;
import java.util.LinkedList;
import javax.swing.SwingUtilities;

/**
 *
 * @author vicente
 */
public class ReporteErrores extends javax.swing.JFrame {
    
    private LinkedList<Errores> listaErrores;

    public ReporteErrores(LinkedList<Errores> listaErrores) {
        this.listaErrores = listaErrores;
        initComponents();
    }

    public ReporteErrores() {
        StringBuilder sb = new StringBuilder();
        for (Errores error : listaErrores) {
            sb.append(error.toString()).append("\n");
        }
        jTextAreaErrores.setText(sb.toString());
    }
    
    public static void reporteErrores(LinkedList<Errores> listaErrores){
        SwingUtilities.invokeLater(() -> {
            ReporteErrores frame = new ReporteErrores(listaErrores);
            frame.setVisible(true);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaErrores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaErrores.setColumns(20);
        jTextAreaErrores.setRows(5);
        jScrollPane1.setViewportView(jTextAreaErrores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaErrores;
    // End of variables declaration//GEN-END:variables
}
